spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: 
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
    properties.hibernate:
      show_sql: true
      format_sql: true
      globally_quoted_identifiers: true


