apiVersion: apps/v1
kind: Deployment
metadata:
  name: igor-news-db-deployment
spec:
  template:
    metadata:
      name: igor-news-db
      labels:
        app: igor-news-db
    spec:
      containers:
        - name: igor-news-bd-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: igor-news-bd-configmap
  replicas: 3
  selector:
    matchLabels:
      app: igor-news-db