apiVersion: v1
kind: Pod
metadata:
  name: igor-news-bd
  labels:
    app: igor-news-bd
spec:
  containers:
    - name: igor-news-bd-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: igor-news-bd-configmap